const restaurantData = [
  {
    restaurantId: 'rest-001',
    name: 'The Burger Lab',
    description: 'Craft burgers made with premium ingredients and bold flavours. Every patty is freshly smashed to order.',
    cuisine: 'American',
    address: '12 MG Road, Bengaluru, Karnataka 560001',
    phone: '9876501001',
    email: 'hello@burgerlab.in',
    ownerId: 'owner-rest-001',
    status: 'active',
    rating: 4.7,
    totalOrders: 0,
    revenue: 0,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop',
    isOpen: true,
    openingTime: '10:00',
    closingTime: '23:00',
    createdAt: new Date().toISOString(),
  },
  {
    restaurantId: 'rest-002',
    name: 'Pizza Paradise',
    description: 'Authentic Italian pizzas baked in a wood-fired oven with imported ingredients straight from Naples.',
    cuisine: 'Italian',
    address: '45 Linking Road, Bandra, Mumbai 400050',
    phone: '9876502002',
    email: 'ciao@pizzaparadise.in',
    ownerId: 'owner-rest-002',
    status: 'active',
    rating: 4.5,
    totalOrders: 0,
    revenue: 0,
    imageUrl: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=400&h=300&fit=crop',
    isOpen: true,
    openingTime: '11:00',
    closingTime: '22:30',
    createdAt: new Date().toISOString(),
  },
];

module.exports = restaurantData;
